project:
  type: book
  output-dir: "docs"
  preview:
    port: 1313
    browser: false

execute: 
  freeze: auto
  cache: true

website:
  favicon: "img/logos/favicon.ico"
  reader-mode: true
  comments: 
    hypothesis:
      theme: clean
      openSidebar: true

book:
  title: "Téncicas Matemáticas en Bioinformática"
  author: "Alfredo Sánchez Alberca"
  date: "1/6/2022"
  output-file: "bioinformatica"
  image: img/logos/sticker-bioinformatica.png
  cover-image: img/logos/sticker-bioinformatica.png
  sharing: [twitter, linkedin]
  downloads: [pdf, epub]
  favicon: "img/logos/favicon.ico"
  sidebar: 
    logo: img/logos/aprendeconalf.png
    tools:
      - icon: house-fill
        href: https://aprendeconalf.es
  open-graph: true
  twitter-card: 
    site: "@aprendeconalf"
  chapters:
    - index.qmd
    - 01-rna-seq.qmd
    - diagrama-volcan.qmd
    
#bibliography: references.bib

format:
  html:
    highlight-style: a11y
    theme:
      dark: [darkly, custom.css]
      light: [flatly, custom.css]
    html-math-method: mathjax
    code-overflow: wrap
  pdf:
    documentclass: scrreport
    papersize: a4
    template-partials:
      - before-body.tex
    titlegraphic: img/logos/sticker-bioinformatica.png
    institution: CEU San Pablo
    email: asalber@ceu.es
    web: https://aprendeconalf.es
    logo: img/logos/aprendeconalf.png
    include-in-header:
      - preamble.tex
      - macros.tex
    keep-tex: true
    #mainfont: TeX Gyre Termes
    #mainfontoptions:
    #  - Numbers=Lowercase
    #  - Numbers=Proportional    
    
  epub:
    cover-image: img/logos/sticker-bioinformatica.png



